import { useEffect, useState } from 'react';
import { X } from 'lucide-react';
import { useAuth } from '../hooks/useAuth';
import { orderApi } from '../services/api';
import { useAppContext } from '../context/AppContext';
import { resolveImageUrl } from '../lib/utils';

export default function ProfileOrderDetailsBridge(){
 const {user}=useAuth();const {formatPrice}=useAppContext();const [order,setOrder]=useState<any>(null);const [busy,setBusy]=useState(false);
 useEffect(()=>{const click=async(event:MouseEvent)=>{const el=(event.target as HTMLElement|null)?.closest('button');if(!el||el.textContent?.trim()!=='View Details'||!user)return;event.preventDefault();event.stopPropagation();setBusy(true);try{const response=await orderApi.getUserOrders(user.uid);const list=Array.isArray(response.data)?response.data:(response.data?.orders||[]);const parent=el.parentElement?.parentElement?.textContent||'';const match=parent.match(/Order\s*#\s*([^\s]+)/i);const found=list.find((item:any)=>String(item.orderNumber||item.id||item._id).endsWith(match?.[1]||''));setOrder(found||null)}catch(error){console.error('[order-details]',error);setOrder(null)}finally{setBusy(false)}};document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true)},[user]);
 if(!order&&!busy)return null;
 return <div className="fixed inset-0 z-[500] flex items-center justify-center p-4"><button aria-label="Close" className="absolute inset-0 bg-black/70 cursor-default" onClick={()=>setOrder(null)}/><div className="relative z-10 w-full max-w-2xl max-h-[88vh] overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between bg-[#080808] p-6 text-white"><div><p className="text-[9px] uppercase tracking-[.25em] text-brand-gold">Order details</p><h3 className="mt-1 text-xl font-serif">#{String(order?.orderNumber||order?.id||order?._id||'').slice(-10)}</h3></div><button onClick={()=>setOrder(null)} className="rounded-full p-2 hover:bg-white/10"><X size={18}/></button></div>{busy?<div className="p-16 text-center text-sm text-gray-500">Loading…</div>:order?<div className="p-6 space-y-6"><div className="grid grid-cols-3 gap-3"><Box label="Status" value={order.status||'Pending'}/><Box label="Currency" value={order.currency||'USD'}/><Box label="Payment" value={order.paymentMethod||'COD'}/></div><div className="space-y-3">{(order.items||[]).map((item:any,index:number)=><div key={index} className="flex gap-4 border-b border-gray-100 pb-3"><div className="h-20 w-16 rounded overflow-hidden bg-gray-100 shrink-0">{(item.image||item.images?.[0])&&<img src={resolveImageUrl(item.image||item.images?.[0])} alt={item.name||'Product'} className="h-full w-full object-cover"/>}</div><div className="flex-1"><p className="font-serif font-bold">{String(item.name||item.title||'Product')}</p><p className="mt-1 text-xs text-gray-500">Qty {Number(item.quantity||1)} · Size {String(item.size||'—')} · Color {String(item.color||'—')}</p></div><p className="font-bold">{formatPrice(Number(item.price||0)*Number(item.quantity||1),order.currency as any)}</p></div>)}</div><div className="rounded-xl bg-[#F8F5EE] p-5 space-y-2"><Box label="Subtotal" value={formatPrice(Number(order.subtotal||0),order.currency as any)}/><Box label="Shipping" value={Number(order.shippingCost||0)?formatPrice(Number(order.shippingCost),order.currency as any):'Complimentary'}/><Box label="Total" value={formatPrice(Number(order.totalAmount||0),order.currency as any)}/></div></div>:<div className="p-16 text-center text-sm text-gray-500">Order details are unavailable.</div>}</div></div>;
}
function Box({label,value}:{label:string,value:any}){return <div className="flex items-center justify-between gap-4"><span className="text-[9px] uppercase tracking-widest text-gray-400">{label}</span><span className="text-sm font-bold">{String(value??'—')}</span></div>}
