import {useEffect,useState} from 'react';
import {Save,RefreshCw,Image as ImageIcon} from 'lucide-react';
import {adminApi} from '../../services/api';
export default function BrandAdmin(){
 const[config,setConfig]=useState<any>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await adminApi.getConfig();setConfig(r.data||{})}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const update=(key:string,value:string)=>setConfig((c:any)=>({...c,branding:{...(c?.branding||{}),[key]:value},header:{...(c?.header||{}),...(key==='brandName'||key==='name'?{logoText:value}:{}),...(key==='logoUrl'?{logoImage:value}:{})},footer:{...(c?.footer||{}),...(key==='brandName'||key==='name'?{brandName:value}:{})}}));
 const save=async()=>{if(!config)return;setSaving(true);try{await adminApi.updateConfig(config);await load()}finally{setSaving(false)}};
 if(loading)return <div className="min-h-screen flex items-center justify-center">Loading brand settings…</div>;
 const b=config?.branding||{};
 return <div className="min-h-screen bg-[#f6f4f0] p-5 md:p-10"><div className="max-w-3xl mx-auto"><div className="flex items-end justify-between gap-4 mb-8"><div><p className="text-[10px] tracking-[.3em] uppercase text-gray-500 font-bold">Global identity</p><h1 className="text-3xl md:text-4xl font-serif mt-2">Brand Studio</h1><p className="text-sm text-gray-500 mt-2">Change the brand identity here and the saved runtime configuration is used across configurable storefront surfaces.</p></div><button onClick={load} className="p-3 border bg-white"><RefreshCw size={18}/></button></div><div className="bg-white border border-gray-200 p-6 md:p-8 space-y-6"><label className="block"><span className="text-xs uppercase tracking-widest text-gray-500">Brand name</span><input value={b.brandName||b.name||''} onChange={e=>{update('brandName',e.target.value);update('name',e.target.value)}} className="mt-2 w-full border border-gray-200 p-3 text-lg font-serif"/></label><label className="block"><span className="text-xs uppercase tracking-widest text-gray-500">Logo URL</span><div className="mt-2 flex gap-3"><input value={b.logoUrl||''} onChange={e=>update('logoUrl',e.target.value)} placeholder="https://…" className="flex-1 border border-gray-200 p-3"/><ImageIcon size={20} className="self-center text-gray-400"/></div></label><label className="block"><span className="text-xs uppercase tracking-widest text-gray-500">Support email</span><input value={b.supportEmail||''} onChange={e=>update('supportEmail',e.target.value)} className="mt-2 w-full border border-gray-200 p-3"/></label><button onClick={save} disabled={saving} className="w-full bg-black text-white py-4 text-xs font-bold uppercase tracking-[.2em] inline-flex items-center justify-center gap-2"><Save size={16}/>{saving?'Saving…':'Save global brand identity'}</button></div></div></div>;
}