import { useEffect,useState } from 'react';
import { Check,X,Trash2,RefreshCw,Plus,Star,EyeOff,Eye,Edit3,Save } from 'lucide-react';
import { reviewApi } from '../../services/api';
export default function ReviewsAdmin(){
 const [reviews,setReviews]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''); const [showAddModal,setShowAddModal]=useState(false); const [newReview,setNewReview]=useState({productId:'',customerName:'',rating:5,comment:''}); const [editing,setEditing]=useState<any>(null);
 const load=async()=>{setLoading(true);setError('');try{const response=await reviewApi.getAdminQueue();setReviews(Array.isArray(response.data?.reviews)?response.data.reviews:[]);}catch(err){console.error('[reviews-admin] load failed',err);setError('Reviews could not be loaded. Please refresh.');setReviews([]);}finally{setLoading(false);}}; useEffect(()=>{load();},[]);
 const setStatus=async(reviewId:string,status:string)=>{setBusy(reviewId);try{await reviewApi.setStatus(reviewId,{status});await load();}catch(err:any){setError(err?.response?.data?.error||'Review update failed.');}finally{setBusy('');}};
 const toggleVisibility=async(reviewId:string,currentVisibility:boolean)=>{setBusy(reviewId);try{await reviewApi.setStatus(reviewId,{isVisible:!currentVisibility});await load();}catch(err:any){setError(err?.response?.data?.error||'Visibility update failed.');}finally{setBusy('');}};
 const remove=async(reviewId:string)=>{if(!confirm('Delete this review permanently? This cannot be undone.'))return;setBusy(reviewId);try{await reviewApi.remove(reviewId);await load();}catch(err:any){setError(err?.response?.data?.error||'Review deletion failed.');}finally{setBusy('');}};
 const saveEdit=async()=>{if(!editing)return;setBusy(editing._id);try{await reviewApi.edit(editing._id,{customerName:editing.customerName,rating:editing.rating,comment:editing.comment});setEditing(null);await load();}catch(err:any){setError(err?.response?.data?.error||'Review edit failed.');}finally{setBusy('');}};
 const addManual=async()=>{if(!newReview.productId||!newReview.customerName||!newReview.comment){setError('Product ID, customer name and review are required.');return;}try{await reviewApi.addManual(newReview);setShowAddModal(false);setNewReview({productId:'',customerName:'',rating:5,comment:''});await load();}catch(err:any){setError(err?.response?.data?.error||'Failed to add review.');}};
 if(loading)return <div className="min-h-screen flex items-center justify-center bg-[#f6f4f0]">Loading reviews…</div>;
 return <div className="min-h-screen bg-[#f6f4f0] p-5 md:p-10"><div className="max-w-6xl mx-auto"><div className="flex items-center justify-between gap-4 mb-8"><div><p className="text-[10px] tracking-[.3em] uppercase text-gray-500 font-bold">Moderation</p><h1 className="text-3xl md:text-4xl font-serif mt-2">Customer Reviews</h1><p className="text-sm text-gray-500 mt-2">Approve, disapprove, hide, edit, publish or permanently delete customer feedback.</p></div><div className="flex gap-3"><button onClick={load} className="p-2 border border-gray-300 bg-white hover:bg-gray-50"><RefreshCw size={18}/></button><button onClick={()=>setShowAddModal(true)} className="bg-gray-900 text-white px-4 py-2 text-xs font-bold tracking-widest uppercase flex items-center gap-2"><Plus size={16}/> Add Review</button></div></div>
 {error&&<div className="mb-6 p-4 bg-red-50 text-red-700 text-sm border border-red-200">{error}</div>}
 {showAddModal&&<div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"><div className="bg-white p-6 max-w-md w-full space-y-4"><h3 className="text-lg font-serif font-bold">Add Manual Review</h3><input className="w-full border p-2 text-sm" placeholder="Product ID" value={newReview.productId} onChange={e=>setNewReview({...newReview,productId:e.target.value})}/><input className="w-full border p-2 text-sm" placeholder="Customer Name" value={newReview.customerName} onChange={e=>setNewReview({...newReview,customerName:e.target.value})}/><select className="w-full border p-2 text-sm" value={newReview.rating} onChange={e=>setNewReview({...newReview,rating:Number(e.target.value)})}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} Stars</option>)}</select><textarea className="w-full border p-2 text-sm" rows={3} placeholder="Review comment" value={newReview.comment} onChange={e=>setNewReview({...newReview,comment:e.target.value})}/><div className="flex gap-2 justify-end"><button onClick={()=>setShowAddModal(false)} className="px-4 py-2 text-sm border">Cancel</button><button onClick={addManual} className="px-4 py-2 text-sm bg-gray-900 text-white">Publish</button></div></div></div>}
 <div className="bg-white border border-gray-200 divide-y divide-gray-100">{reviews.length===0?<div className="p-10 text-center text-gray-500 text-sm">No reviews found in the system.</div>:reviews.map(review=><div key={review._id} className="p-5 flex flex-col md:flex-row gap-4 items-start md:items-center justify-between"><div className="flex-1 space-y-2"><div className="flex items-center gap-2"><div className="flex text-yellow-500">{[...Array(5)].map((_,i)=><Star key={i} size={14} fill={i<review.rating?'currentColor':'none'}/>)}</div><span className="text-xs text-gray-400 uppercase tracking-wider">{review.status}</span>{review.isManual&&<span className="text-[10px] bg-gray-100 px-2 py-0.5 uppercase tracking-wider">Manual</span>}</div>{editing?._id===review._id?<div className="space-y-2"><input className="w-full border p-1 text-sm" value={editing.customerName} onChange={e=>setEditing({...editing,customerName:e.target.value})}/><textarea className="w-full border p-1 text-sm" rows={2} value={editing.comment} onChange={e=>setEditing({...editing,comment:e.target.value})}/></div>:<><p className="font-semibold text-sm">{review.customerName}</p><p className="text-sm text-gray-600 italic">"{review.comment}"</p><p className="text-[10px] text-gray-400">Product: {review.productId?.title||review.productId?.name||review.productId}</p></>}</div><div className="flex items-center gap-2 shrink-0">{editing?._id===review._id?<button onClick={saveEdit} disabled={!!busy} className="p-2 bg-green-600 text-white"><Save size={16}/></button>:<button onClick={()=>setEditing(review)} disabled={!!busy} className="p-2 border hover:bg-gray-50" title="Edit"><Edit3 size={16}/></button>}<button onClick={()=>toggleVisibility(review._id,review.isVisible)} disabled={!!busy} className={`p-2 border ${review.isVisible?'text-gray-900':'text-gray-400'}`} title={review.isVisible?'Hide':'Unhide'}>{review.isVisible?<Eye size={16}/>:<EyeOff size={16}/>}</button>{review.status!=='approved'&&<button onClick={()=>setStatus(review._id,'approved')} disabled={!!busy} className="p-2 border border-green-200 text-green-700 hover:bg-green-50" title="Approve"><Check size={16}/></button>}{review.status!=='disapproved'&&<button onClick={()=>setStatus(review._id,'disapproved')} disabled={!!busy} className="p-2 border border-red-200 text-red-700 hover:bg-red-50" title="Disapprove"><X size={16}/></button>}<button onClick={()=>remove(review._id)} disabled={!!busy} className="p-2 border border-red-200 text-red-700 hover:bg-red-50" title="Delete Permanently"><Trash2 size={16}/></button></div></div>)}</div></div></div>;
}
