import {useEffect,useState}from 'react';
import {Check,X,Trash2,RefreshCw,Plus,Star}from 'lucide-react';
import {productApi,reviewApi} from '../../services/api';

export default function ReviewsAdmin(){
  const[reviews,setReviews]=useState<any[]>([]);const[products,setProducts]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');
  const[productId,setProductId]=useState('');const[name,setName]=useState('');const[comment,setComment]=useState('');const[rating,setRating]=useState(5);
  const load=async()=>{setLoading(true);try{const [queue,productResponse]=await Promise.all([reviewApi.getAdminQueue(),productApi.getAll()]);setReviews(queue.data?.reviews||[]);const rows=productResponse.data?.products||productResponse.data||[];setProducts(Array.isArray(rows)?rows:[]);}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const update=async(review:any,status:'approved'|'rejected')=>{setBusy(review.reviewId);try{await reviewApi.setStatus(review.productId,review.reviewId,status);await load();}finally{setBusy('');}};
  const remove=async(review:any)=>{if(!confirm('Delete this review permanently?'))return;setBusy(review.reviewId);try{await reviewApi.remove(review.productId,review.reviewId);await load();}finally{setBusy('');}};
  const addEditorial=async()=>{if(!productId||!name.trim()||!comment.trim())return;setBusy('editorial');try{await reviewApi.addEditorial(productId,{customerName:name.trim(),comment:comment.trim(),rating});setName('');setComment('');setRating(5);await load();}finally{setBusy('');}};
  const pending=reviews.filter(r=>r.status==='pending'), published=reviews.filter(r=>r.status==='approved'), rejected=reviews.filter(r=>r.status==='rejected');
  const ReviewCard=({review}:{review:any})=><article className="bg-white border border-gray-200 p-5"><div className="flex justify-between gap-4"><div><div className="font-semibold text-brand-dark">{review.customerName}</div><div className="text-xs text-gray-400 mt-1">{review.email||'Editorial entry'} · {review.productName}</div></div><div className="flex text-brand-gold">{[1,2,3,4,5].map(n=><Star key={n} size={13} fill={n<=Number(review.rating)?'currentColor':'none'}/>)}</div></div><p className="text-sm leading-6 text-gray-600 mt-4">{review.comment}</p><div className="mt-5 flex flex-wrap gap-2">{review.status==='pending'&&<><button disabled={busy===review.reviewId} onClick={()=>update(review,'approved')} className="px-3 py-2 text-xs font-bold bg-green-700 text-white inline-flex items-center gap-1"><Check size={14}/>Approve</button><button disabled={busy===review.reviewId} onClick={()=>update(review,'rejected')} className="px-3 py-2 text-xs font-bold bg-gray-800 text-white inline-flex items-center gap-1"><X size={14}/>Reject</button></>}<button disabled={busy===review.reviewId} onClick={()=>remove(review)} className="px-3 py-2 text-xs font-bold border border-red-200 text-red-700 inline-flex items-center gap-1"><Trash2 size={14}/>Delete</button></div></article>;
  return <div className="min-h-screen bg-[#f6f4f0] p-5 md:p-10"><div className="max-w-7xl mx-auto"><div className="flex items-end justify-between gap-5 mb-8"><div><p className="text-[10px] tracking-[.3em] uppercase text-brand-gold font-bold">Content moderation</p><h1 className="text-3xl md:text-4xl font-serif text-brand-dark mt-2">Review Studio</h1><p className="text-sm text-gray-500 mt-2">Customer submissions stay private until approved.</p></div><button onClick={load} className="p-3 border border-gray-200 bg-white"><RefreshCw size={18} className={loading?'animate-spin':''}/></button></div>
  <section className="grid lg:grid-cols-3 gap-6 mb-8"><div className="bg-white border border-gray-200 p-6"><div className="text-3xl font-serif">{pending.length}</div><div className="text-xs uppercase tracking-widest text-gray-400 mt-2">Awaiting review</div></div><div className="bg-white border border-gray-200 p-6"><div className="text-3xl font-serif">{published.length}</div><div className="text-xs uppercase tracking-widest text-gray-400 mt-2">Published</div></div><div className="bg-white border border-gray-200 p-6"><div className="text-3xl font-serif">{rejected.length}</div><div className="text-xs uppercase tracking-widest text-gray-400 mt-2">Rejected</div></div></section>
  <section className="bg-white border border-gray-200 p-6 md:p-8 mb-8"><div className="flex items-center gap-2 mb-5"><Plus size={18}/><h2 className="font-serif text-2xl">Add curated editorial note</h2></div><p className="text-sm text-gray-500 mb-5">Use this only for clearly curated editorial content. Do not present fabricated testimonials as verified customer reviews.</p><div className="grid md:grid-cols-2 gap-4"><select value={productId} onChange={e=>setProductId(e.target.value)} className="border border-gray-200 p-3 bg-white"><option value="">Choose product</option>{products.map((p:any)=><option key={p.id||p._id} value={p.id||p._id}>{p.title||p.name}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} placeholder="Editorial attribution" className="border border-gray-200 p-3"/></div><textarea value={comment} onChange={e=>setComment(e.target.value)} rows={4} placeholder="Editorial note" className="w-full border border-gray-200 p-3 mt-4"/><div className="flex items-center justify-between mt-4"><div className="flex text-brand-gold">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)}><Star size={20} fill={n<=rating?'currentColor':'none'}/></button>)}</div><button disabled={busy==='editorial'} onClick={addEditorial} className="bg-brand-dark text-white px-6 py-3 text-xs font-bold uppercase tracking-widest">{busy==='editorial'?'Saving…':'Save editorial note'}</button></div></section>
  <section><h2 className="font-serif text-2xl mb-5">Pending submissions</h2><div className="grid md:grid-cols-2 gap-5">{pending.length?pending.map(r=><ReviewCard key={r.reviewId} review={r}/>):<div className="text-sm text-gray-500 py-10">No reviews are waiting for approval.</div>}</div></section>
  <section className="mt-10"><h2 className="font-serif text-2xl mb-5">Published</h2><div className="grid md:grid-cols-2 gap-5">{published.map(r=><ReviewCard key={r.reviewId} review={r}/>)}</div></section>
  </div></div>;
}