import {useEffect,useState}from 'react';
import {Check,X,Trash2,RefreshCw,Plus,Star,EyeOff,Edit3,Save}from 'lucide-react';
import {productApi,reviewApi} from '../../services/api';

export default function ReviewsAdmin(){
 const[reviews,setReviews]=useState<any[]>([]);const[products,setProducts]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[editing,setEditing]=useState<any|null>(null);
 const[productId,setProductId]=useState('');const[name,setName]=useState('');const[comment,setComment]=useState('');const[rating,setRating]=useState(5);
 const load=async()=>{setLoading(true);try{const [queue,productResponse]=await Promise.all([reviewApi.getAdminQueue(),productApi.getAll()]);setReviews(queue.data?.reviews||[]);const rows=productResponse.data?.products||productResponse.data||[];setProducts(Array.isArray(rows)?rows:[]);}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const setStatus=async(review:any,status:any)=>{setBusy(review.reviewId);try{await reviewApi.setStatus(review.productId,review.reviewId,status);await load()}finally{setBusy('')}};
 const remove=async(review:any)=>{if(!confirm('Delete this review permanently?'))return;setBusy(review.reviewId);try{await reviewApi.remove(review.productId,review.reviewId);await load()}finally{setBusy('')}};
 const saveEdit=async()=>{if(!editing)return;setBusy(editing.reviewId);try{await reviewApi.edit(editing.productId,editing.reviewId,{customerName:editing.customerName,comment:editing.comment,rating:editing.rating,status:editing.status});setEditing(null);await load()}finally{setBusy('')}};
 const addEditorial=async()=>{if(!productId||!name.trim()||!comment.trim())return;setBusy('editorial');try{await reviewApi.addEditorial(productId,{customerName:name.trim(),comment:comment.trim(),rating});setName('');setComment('');setRating(5);await load()}finally{setBusy('')}};
 const pending=reviews.filter(r=>r.status==='pending'),published=reviews.filter(r=>r.status==='approved'),hidden=reviews.filter(r=>r.status==='hidden'||r.status==='rejected');
 const ReviewCard=({review}:{review:any})=><article className="bg-white border border-gray-200 p-5 shadow-[0_18px_45px_-38px_rgba(0,0,0,.6)]"><div className="flex justify-between gap-4"><div><div className="font-semibold text-brand-dark">{review.customerName}</div><div className="text-xs text-gray-400 mt-1">{review.email||'Manual entry'} · {review.productName}</div></div><div className="flex text-brand-gold">{[1,2,3,4,5].map(n=><Star key={n} size={13} fill={n<=Number(review.rating)?'currentColor':'none'}/>)}</div></div><p className="text-sm leading-6 text-gray-600 mt-4">{review.comment}</p><div className="mt-5 flex flex-wrap gap-2">{review.status!=='approved'&&<button disabled={busy===review.reviewId} onClick={()=>setStatus(review,'approved')} className="px-3 py-2 text-xs font-bold bg-green-700 text-white inline-flex items-center gap-1"><Check size={14}/>Approve</button>}<button disabled={busy===review.reviewId} onClick={()=>setStatus(review,'hidden')} className="px-3 py-2 text-xs font-bold bg-gray-800 text-white inline-flex items-center gap-1"><EyeOff size={14}/>Hide</button><button onClick={()=>setEditing({...review})} className="px-3 py-2 text-xs font-bold border border-gray-200 inline-flex items-center gap-1"><Edit3 size={14}/>Edit</button><button disabled={busy===review.reviewId} onClick={()=>remove(review)} className="px-3 py-2 text-xs font-bold border border-red-200 text-red-700 inline-flex items-center gap-1"><Trash2 size={14}/>Delete</button></div></article>;
 return <div className="min-h-screen bg-[#f6f4f0] p-5 md:p-10"><div className="max-w-7xl mx-auto"><div className="flex items-end justify-between gap-5 mb-8"><div><p className="text-[10px] tracking-[.3em] uppercase text-gray-500 font-bold">Customer content</p><h1 className="text-3xl md:text-4xl font-serif text-brand-dark mt-2">Review Studio</h1><p className="text-sm text-gray-500 mt-2">Approve, hide, edit or remove reviews before they become part of the public collection.</p></div><button onClick={load} className="p-3 border border-gray-200 bg-white"><RefreshCw size={18} className={loading?'animate-spin':''}/></button></div>
 <section className="grid lg:grid-cols-3 gap-6 mb-8"><div className="bg-white border border-gray-200 p-6"><div className="text-3xl font-serif">{pending.length}</div><div className="text-xs uppercase tracking-widest text-gray-400 mt-2">New submissions</div></div><div className="bg-white border border-gray-200 p-6"><div className="text-3xl font-serif">{published.length}</div><div className="text-xs uppercase tracking-widest text-gray-400 mt-2">Visible</div></div><div className="bg-white border border-gray-200 p-6"><div className="text-3xl font-serif">{hidden.length}</div><div className="text-xs uppercase tracking-widest text-gray-400 mt-2">Hidden</div></div></section>
 <section className="bg-white border border-gray-200 p-6 md:p-8 mb-8"><div className="flex items-center gap-2 mb-5"><Plus size={18}/><h2 className="font-serif text-2xl">Add a review entry</h2></div><p className="text-sm text-gray-500 mb-5">Manual entries are editable from this studio at any time.</p><div className="grid md:grid-cols-2 gap-4"><select value={productId} onChange={e=>setProductId(e.target.value)} className="border border-gray-200 p-3 bg-white"><option value="">Choose product</option>{products.map((p:any)=><option key={p.id||p._id} value={p.id||p._id}>{p.title||p.name}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} placeholder="Customer name" className="border border-gray-200 p-3"/></div><textarea value={comment} onChange={e=>setComment(e.target.value)} rows={4} placeholder="Review" className="w-full border border-gray-200 p-3 mt-4"/><div className="flex items-center justify-between mt-4"><div className="flex text-brand-gold">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)}><Star size={20} fill={n<=rating?'currentColor':'none'}/></button>)}</div><button disabled={busy==='editorial'} onClick={addEditorial} className="bg-brand-dark text-white px-6 py-3 text-xs font-bold uppercase tracking-widest">{busy==='editorial'?'Saving…':'Add review'}</button></div></section>
 <section><h2 className="font-serif text-2xl mb-5">New customer reviews</h2><div className="grid md:grid-cols-2 gap-5">{pending.length?pending.map(r=><ReviewCard key={r.reviewId} review={r}/>):<div className="text-sm text-gray-500 py-10">No new reviews right now.</div>}</div></section>
 <section className="mt-10"><h2 className="font-serif text-2xl mb-5">Visible reviews</h2><div className="grid md:grid-cols-2 gap-5">{published.map(r=><ReviewCard key={r.reviewId} review={r}/>)}</div></section>
 <section className="mt-10"><h2 className="font-serif text-2xl mb-5">Hidden reviews</h2><div className="grid md:grid-cols-2 gap-5">{hidden.map(r=><ReviewCard key={r.reviewId} review={r}/>)}</div></section>
 {editing&&<div className="fixed inset-0 z-[200] bg-black/50 flex items-center justify-center p-4"><div className="w-full max-w-xl bg-white p-6 shadow-2xl"><div className="flex justify-between items-center mb-5"><h2 className="font-serif text-2xl">Edit review</h2><button onClick={()=>setEditing(null)}><X size={20}/></button></div><input value={editing.customerName||''} onChange={e=>setEditing({...editing,customerName:e.target.value})} className="w-full border border-gray-200 p-3 mb-3"/><textarea value={editing.comment||''} onChange={e=>setEditing({...editing,comment:e.target.value})} rows={5} className="w-full border border-gray-200 p-3"/><div className="flex justify-between items-center mt-4"><select value={editing.status||'pending'} onChange={e=>setEditing({...editing,status:e.target.value})} className="border p-3"><option value="pending">Pending</option><option value="approved">Visible</option><option value="hidden">Hidden</option><option value="rejected">Disapproved</option></select><button onClick={saveEdit} disabled={busy===editing.reviewId} className="bg-black text-white px-5 py-3 text-xs font-bold uppercase tracking-widest inline-flex gap-2 items-center"><Save size={15}/>Save changes</button></div></div></div>}
 </div></div>;
}